[package]
name = "bondnet-client"
version = "0.1.0"
edition = "2024"

[dependencies]
bondnet-protocol = { version = "0.1.0", path = "../bondnet-protocol" }
tokio = { version = "1.53.1", features = ["net", "rt", "rt-multi-thread", "macros", "signal", "sync", "time"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_System_Diagnostics_Debug", "Win32_System_LibraryLoader", "Win32_System_Threading"] }
